version: "1.0"

services:
  postgres:
    image: postgres:12.8-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
      - PSQL_HISTFILE=/root/log/.psql_history
    ports:
      - "5442:5432"
    healthcheck:
      test: pg_isready --username=postgres --host=127.0.0.1
      interval: 5s

volumes:
  postgres:
